export const products = [
  {
    id: "black-masterbatch",
    titleFa: "مستربچ مشکی",
    titleEn: "Black Masterbatch",
    category: "masterbatch",
    categoryFa: "مستربچ",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=600&q=80",
    grades: ["NaNo-Grade F40", "F40C10", "F35C20"],
    descFa: "مستربچ مشکی نوین اندیش بسپار شیراز بر پایه پلیمرهای مهندسی شده با غلظت بالای کربن بلک و توزیع یکنواخت طراحی شده است که پوشش دهی عالی، براقیت و مقاومت در برابر اشعه UV را فراهم می کند.",
    descEn: "Novin Andish Baspar Shiraz Black Masterbatch is formulated with high carbon black concentration and excellent dispersion, offering high opacity, gloss, and UV resistance.",
    applicationsFa: "فیلم‌های ژئوممبران، لوله‌های آبیاری، کیسه‌های بسته‌بندی، قطعات خودرو",
    applicationsEn: "Geomembrane films, irrigation pipes, packaging bags, automotive parts",
    dosageFa: "۱٪ تا ۵٪ (بسته به کاربرد نهایی و ضخامت قطعه)",
    dosageEn: "1% to 5% (depending on application and thickness)",
    compatibilityFa: "LDPE, LLDPE, HDPE, PP",
    compatibilityEn: "LDPE, LLDPE, HDPE, PP",
    storageFa: "محیط خشک و خنک، دمای ۱۵ تا ۳۰ درجه سانتی‌گراد، دور از نور مستقیم خورشید و رطوبت روی پالت",
    storageEn: "Dry and cool warehouse, 15-30°C, kept on pallets away from direct sunlight"
  },
  {
    id: "white-masterbatch",
    titleFa: "مستربچ سفید",
    titleEn: "White Masterbatch",
    category: "masterbatch",
    categoryFa: "مستربچ",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    grades: ["WT 70", "WT 60", "WT 50", "WT 1065", "WT 3045", "WT 5025"],
    descFa: "مستربچ سفید نوین اندیش بسپار شیراز بر پایه دی اکسید تیتانیوم (TiO2) با کیفیت بالا، سفیدی، پوشش دهی و درخشندگی استثنایی را در محصولات پلاستیکی تضمین می کند.",
    descEn: "Novin Andish Baspar Shiraz White Masterbatch is based on premium Titanium Dioxide (TiO2), ensuring exceptional whiteness, opacity, and brightness in plastic products.",
    applicationsFa: "ظروف یکبار مصرف، بسته‌بندی لبنیات، فیلم‌های چند لایه، بطری‌های پلاستیکی",
    applicationsEn: "Disposable containers, dairy packaging, multilayer films, plastic bottles",
    dosageFa: "۱٪ تا ۴٪",
    dosageEn: "1% to 4%",
    compatibilityFa: "LDPE, HDPE, PP, GPPS",
    compatibilityEn: "LDPE, HDPE, PP, GPPS",
    storageFa: "محیط خشک و خنک، دور از رطوبت شدید و نور مستقیم",
    storageEn: "Cool and dry space, protected from high humidity and direct sunlight"
  },
  {
    id: "calcium-carbonate-filler",
    titleFa: "مستربچ کربنات کلسیم",
    titleEn: "Calcium Carbonate Filler",
    category: "filler",
    categoryFa: "پر کننده",
    image: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=600&q=80",
    grades: ["CaCO3 Grade C80", "CaCO3 Grade C70"],
    descFa: "مستربچ پرکننده کربنات کلسیم (CaCO3) نوین اندیش بسپار شیراز برای کاهش هزینه‌های تولید و بهبود خواص فیزیکی مانند سختی، مقاومت حرارتی و کاهش انقباض در محصولات پلیمری طراحی شده است.",
    descEn: "Novin Andish Baspar Shiraz Calcium Carbonate (CaCO3) Filler Masterbatch is designed to reduce manufacturing costs while improving physical properties like stiffness, thermal resistance, and shrinkage reduction.",
    applicationsFa: "تولید نایلون و نایلکس، لوله‌های ساختمانی، قطعات تزریقی، گونی‌بافی و ظروف بسته‌بندی",
    applicationsEn: "Nylon and bags, construction pipes, injection-molded parts, woven sacks, packaging containers",
    dosageFa: "۵٪ تا ۵۰٪ (بسته به فرآیند تولید و ضخامت فیلم)",
    dosageEn: "5% to 50% (depending on the manufacturing process and thickness)",
    compatibilityFa: "PE, PP",
    compatibilityEn: "PE, PP",
    storageFa: "محیط خشک و بدون رطوبت، نگهداری روی پالت برای جلوگیری از جذب رطوبت زمین",
    storageEn: "Moisture-free environment, stored on pallets to prevent moisture absorption from floor"
  },
  {
    id: "optical-brightener",
    titleFa: "مستربچ براق کننده",
    titleEn: "Optical Brightener",
    category: "additive",
    categoryFa: "افزودنی",
    image: "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?auto=format&fit=crop&w=600&q=80",
    grades: ["OB Grade 10", "OB Grade 20"],
    descFa: "مستربچ براق کننده نوین اندیش بسپار شیراز با جذب اشعه ماوراء بنفش و انتشار نور آبی، زردی پلاستیک‌ها را پوشش داده و باعث افزایش شفافیت، درخشندگی و زنده شدن رنگ محصولات می‌شود.",
    descEn: "Novin Andish Baspar Shiraz Optical Brightener Masterbatch absorbs UV light and emits blue fluorescence, masking polymer yellowness and significantly enhancing product brightness and color vitality.",
    applicationsFa: "محصولات بازیافتی، قطعات پلاستیکی شفاف، ظروف بسته‌بندی، نایلون‌های لوکس زراعی و تجاری",
    applicationsEn: "Recycled products, transparent plastic items, packaging containers, high-end agricultural films",
    dosageFa: "۰٫۱٪ تا ۰٫۵٪",
    dosageEn: "0.1% to 0.5%",
    compatibilityFa: "PE, PP, PS, ABS",
    compatibilityEn: "PE, PP, PS, ABS",
    storageFa: "محیط خنک و دور از تابش آفتاب (به دلیل حساسیت نوری ماده افزودنی)",
    storageEn: "Cool space, protected from UV exposure due to the additive's light sensitivity"
  },
  {
    id: "slip-masterbatch",
    titleFa: "مستربچ لیز کننده",
    titleEn: "Slip Masterbatch",
    category: "additive",
    categoryFa: "افزودنی",
    image: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=600&q=80",
    grades: ["Slip Grade S10", "Slip Grade S20"],
    descFa: "مستربچ لیز کننده نوین اندیش بسپار شیراز با کاهش ضریب اصطکاک سطحی پلاستیک‌ها، از چسبندگی فیلم‌ها در فرآیند تولید و انبارداری جلوگیری کرده و سرعت خط تولید را افزایش می‌دهد بدون این که شفافیت محصول کم شود.",
    descEn: "Novin Andish Baspar Shiraz Slip Masterbatch reduces the coefficient of friction of plastics, preventing film sticking during production and storage, thus accelerating line speed without sacrificing transparency.",
    applicationsFa: "فیلم‌های بسته‌بندی تک لایه و چند لایه، نایلون‌های کشاورزی، درب بطری‌ها و قطعات سرنده",
    applicationsEn: "Monolayer and multilayer packaging films, agricultural films, bottle caps",
    dosageFa: "۰٫۵٪ تا ۲٪",
    dosageEn: "0.5% to 2%",
    compatibilityFa: "LDPE, LLDPE, HDPE, PP",
    compatibilityEn: "LDPE, LLDPE, HDPE, PP",
    storageFa: "محیط خشک و خنک، کمتر از ۳۰ درجه سانتی‌گراد، درب کیسه همیشه بسته باشد",
    storageEn: "Dry and cool space under 30°C, bag must remain tightly sealed when not in use"
  },
  {
    id: "scented-masterbatch",
    titleFa: "مستربچ خوشبو کننده",
    titleEn: "Fragrance Masterbatch",
    category: "additive",
    categoryFa: "افزودنی",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    grades: ["Lemon Scent L100", "Lavender Scent LV200", "Jasmine Scent J300"],
    descFa: "مستربچ خوشبو کننده نوین اندیش بسپار شیراز حاوی اسانس‌های بادوام است که بوی نامطبوع پلیمرهای پایه یا مواد بازیافتی را از بین برده و رایحه مطبوعی به محصول نهایی می‌دهد.",
    descEn: "Novin Andish Baspar Shiraz Fragrance Masterbatch contains long-lasting scents to neutralize unpleasant base polymer or recycled odors, leaving a pleasant scent in the final product.",
    applicationsFa: "کیسه‌های زباله عطری، نایلون‌های خوشبو، اسباب بازی‌ها، قطعات داخلی خودرو و تبلیغاتی",
    applicationsEn: "Scented garbage bags, fragrant plastic films, toys, automotive interior parts",
    dosageFa: "۱٪ تا ۳٪",
    dosageEn: "1% to 3%",
    compatibilityFa: "PE, PP, EVA",
    compatibilityEn: "PE, PP, EVA",
    storageFa: "محیط کاملاً مهر و موم شده، خنک و خشک برای جلوگیری از هدر رفتن رایحه و اسانس",
    storageEn: "Airtight packaging, cool and dry storage to preserve scent intensity"
  },
  {
    id: "antioxidant-rejuvenation",
    titleFa: "مستربچ احیا کننده",
    titleEn: "Antioxidant Rejuvenation",
    category: "additive",
    categoryFa: "افزودنی",
    image: "https://images.unsplash.com/photo-1532187863486-abf9d39d66e8?auto=format&fit=crop&w=600&q=80",
    grades: ["Antioxidant AO10", "Stabilizer HS20"],
    descFa: "مستربچ احیا کننده و آنتی اکسیدان مانع از تخریب حرارتی پلیمرها در فرآیند اکستروژن و تولید قطعات شده و به افزایش طول عمر محصولات و امکان استفاده بهینه از مواد بازیافتی کمک می‌کند.",
    descEn: "Antioxidant Rejuvenation Masterbatch prevents thermal degradation of polymers during extrusion, extending product lifespan and facilitating efficient usage of recycled polymers.",
    applicationsFa: "لوله‌های پلی‌اتیلنی طولانی‌مدت، مخازن ذخیره آب، قطعات بیرونی خودرو، لوازم خانگی و کشاورزی",
    applicationsEn: "Long-term PE pipes, water storage tanks, automotive exterior components, household items",
    dosageFa: "۰٫۵٪ تا ۱٫۵٪",
    dosageEn: "0.5% to 1.5%",
    compatibilityFa: "HDPE, LDPE, PP",
    compatibilityEn: "HDPE, LDPE, PP",
    storageFa: "محیط خشک و خنک و دور از تماس با مواد اسیدی یا اکسیدکننده‌های قوی",
    storageEn: "Dry and cool warehouse, isolated from acidic materials or strong oxidizers"
  }
];

export const articles = [
  {
    id: "cost-saving",
    titleFa: "چگونه می‌توان بدون افت کیفیت هزینه تولید را کاهش داد؟",
    dateFa: "۱۹ بهمن ۱۴۰۴",
    summaryFa: "در این مقاله راهکارهای بهینه‌سازی فرمولاسیون مستربچ‌ها و پرکننده‌ها برای کاهش هزینه‌های بسته‌بندی و پلیمری بررسی شده است.",
    readTime: "۵ دقیقه"
  },
  {
    id: "nanostructure-pioneer",
    titleFa: "شرکت نوین اندیش بسپار شیراز پیشگام مستربچ های نانوساختار",
    dateFa: "۳ دی ۱۴۰۴",
    summaryFa: "تکنولوژی نانو در مستربچ‌ها کیفیت پوشش‌دهی و مقاومت فیزیکی قطعات پلیمری را دگرگون ساخته است. ما در این مسیر پیشتازیم.",
    readTime: "۷ دقیقه"
  },
  {
    id: "knowledge-based-certificate",
    titleFa: "شرکت نوین اندیش بسپار شیراز مسیرنوآوری با گواهی دانش بنیان",
    dateFa: "۳ دی ۱۴۰۴",
    summaryFa: "دریافت گواهی رسمی دانش‌بنیان، گامی نوین در توسعه فرمولاسیون‌های استراتژیک افزودنی‌های پلیمری است.",
    readTime: "۴ دقیقه"
  }
];
